name: Notify on Push

on:
  push:
    branches:
      - "**"  # 所有分支更新都会触发

jobs:
  send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook notification
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "repository": "${{ github.repository }}",
              "pusher": "${{ github.actor }}",
              "branch": "${{ github.ref_name }}",
              "commit_message": "${{ github.event.head_commit.message }}",
              "commit_url": "${{ github.event.head_commit.url }}"
            }'

